Non-deterministic collection initialization fixed
OrleansContrib/Orleans.Providers.MongoDB pull request #133
Opened 2024-02-13 16:06 UTC by NorekZ

Fixed:
1) Collection creation in advance is not needed and this implementation could cause race condition when multiple services starts at the same time.
2) When collection was initializing during mongo startup, method inside Lazy thrown exception, that was cached forever. My implementation tries to initialize collection until it succeeds.

2024-03-04 17:21 UTC, ReubenBond approved these changes

2024-03-04 20:29 UTC, wassim-k requested changes

2024-03-04 20:42 UTC, wassim-k approved these changes

2024-03-05 02:35 UTC, merged

2024-03-05 08:31 UTC, NorekZ commented on Orleans.Providers.MongoDB/Utils/CollectionBase.cs
> +                    mongoClient.GetDatabase("admin").RunCommand<BsonDocument>(new BsonDocument
IMO yes, altough we actually don't use (Cosmos) sharding, it seems like a merge fault in a git history
see: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/commit/929093d991fca428c82f5190c43b471eff70d801 which fixed a bug
and then https://github.com/OrleansContrib/Orleans.Providers.MongoDB/commit/d8dd92b12251ed7ff60b2714c52280518d88bc6f IMO accidentally removed it

either way, previous code didn't work for sure

2024-03-05 09:41 UTC, wassim-k commented on Orleans.Providers.MongoDB/Utils/CollectionBase.cs
> +                    mongoClient.GetDatabase("admin").RunCommand<BsonDocument>(new BsonDocument
Great work, thanks for fixing it 👍